/** Tipi di miele — in ordine alfabetico */
export const HONEY_TYPES = [
  'Acacia (Robinia)',
  'Arancio (Agrumi)',
  'Cardo',
  'Castagno',
  'Colza',
  'Corbezzolo',
  'Edera',
  'Erba Santa',
  'Eucalipto',
  'Girasole',
  'Lavanda',
  'Loietto',
  'Lupinella',
  'Melata',
  'Melata di Abete',
  'Melata di Metcalfa',
  'Melata di Pino',
  'Melata di Quercia',
  'Melata di Salice',
  'Miele di Bosco',
  'Miele di Montagna',
  'Millefiori',
  'Millefiori d\'Estate',
  'Millefiori di Primavera',
  'Nepeta (Gattaria)',
  'Rhododendron',
  'Rosmarino',
  'Sulla',
  'Tarassaco',
  'Tiglio',
  'Timo',
  'Trifoglio',
] as const

export type HoneyType = (typeof HONEY_TYPES)[number]
