/** Tipi di miele riconosciuti — lista esaustiva ordine di popolarità in Italia */
export const HONEY_TYPES = [
  'Acacia (Robinia)',
  'Millefiori',
  'Castagno',
  'Melata',
  'Sulla',
  'Girasole',
  'Tiglio',
  'Rhododendron',
  'Arancio (Agrumi)',
  'Eucalipto',
  'Tarassaco',
  'Lavanda',
  'Rosmarino',
  'Erba Santa',
  'Lupinella',
  'Trifoglio',
  'Colza',
  'Corbezzolo',
  'Cardo',
  'Melata di Metcalfa',
  'Millefiori di Primavera',
  'Millefiori d\'Estate',
  'Miele di Bosco',
  'Miele di Montagna',
  'Loietto',
  'Timo',
  'Edera',
  'Nepeta (Gattaria)',
  'Melata di Quercia',
  'Melata di Abete',
  'Melata di Pino',
  'Melata di Salice',
] as const

export type HoneyType = (typeof HONEY_TYPES)[number]
