/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticheRouteImport } from './routes/statistiche'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PrevisioniRouteImport } from './routes/previsioni'
import { Route as PiuRouteImport } from './routes/piu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as TrattamentiNewRouteImport } from './routes/trattamenti.new'
import { Route as RaccoltiNewRouteImport } from './routes/raccolti.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiariesNewRouteImport } from './routes/apiaries.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminAttivitaRouteImport } from './routes/admin.attivita'
import { Route as AuthTrattamentiRouteImport } from './routes/_auth.trattamenti'
import { Route as AuthRaccoltiRouteImport } from './routes/_auth.raccolti'
import { Route as AuthHomeRouteImport } from './routes/_auth.home'
import { Route as AuthCalendarioRouteImport } from './routes/_auth.calendario'
import { Route as AuthArnieRouteImport } from './routes/_auth.arnie'
import { Route as TrattamentiTreatmentIdEditRouteImport } from './routes/trattamenti.$treatmentId.edit'
import { Route as RaccoltiHarvestIdEditRouteImport } from './routes/raccolti.$harvestId.edit'
import { Route as InspectionsHiveIdNewRouteImport } from './routes/inspections.$hiveId.new'
import { Route as HivesHiveIdEditRouteImport } from './routes/hives.$hiveId.edit'
import { Route as ApiariesApiaryIdSuggerimentiRouteImport } from './routes/apiaries.$apiaryId.suggerimenti'
import { Route as ApiariesApiaryIdMeteoRouteImport } from './routes/apiaries.$apiaryId.meteo'
import { Route as ApiariesApiaryIdEditRouteImport } from './routes/apiaries.$apiaryId.edit'
import { Route as AuthApiariesApiaryIdRouteImport } from './routes/_auth.apiaries.$apiaryId'
import { Route as HivesHiveIdInspectionsInspectionIdRouteImport } from './routes/hives.$hiveId.inspections.$inspectionId'
import { Route as ApiariesApiaryIdHivesNewRouteImport } from './routes/apiaries.$apiaryId.hives.new'
import { Route as AuthHivesHiveIdInspectionsRouteImport } from './routes/_auth.hives.$hiveId.inspections'

const StatisticheRoute = StatisticheRouteImport.update({
  id: '/statistiche',
  path: '/statistiche',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisioniRoute = PrevisioniRouteImport.update({
  id: '/previsioni',
  path: '/previsioni',
  getParentRoute: () => rootRouteImport,
} as any)
const PiuRoute = PiuRouteImport.update({
  id: '/piu',
  path: '/piu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const TrattamentiNewRoute = TrattamentiNewRouteImport.update({
  id: '/trattamenti/new',
  path: '/trattamenti/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RaccoltiNewRoute = RaccoltiNewRouteImport.update({
  id: '/raccolti/new',
  path: '/raccolti/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiariesNewRoute = ApiariesNewRouteImport.update({
  id: '/apiaries/new',
  path: '/apiaries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttivitaRoute = AdminAttivitaRouteImport.update({
  id: '/admin/attivita',
  path: '/admin/attivita',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTrattamentiRoute = AuthTrattamentiRouteImport.update({
  id: '/trattamenti',
  path: '/trattamenti',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRaccoltiRoute = AuthRaccoltiRouteImport.update({
  id: '/raccolti',
  path: '/raccolti',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarioRoute = AuthCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArnieRoute = AuthArnieRouteImport.update({
  id: '/arnie',
  path: '/arnie',
  getParentRoute: () => AuthRoute,
} as any)
const TrattamentiTreatmentIdEditRoute =
  TrattamentiTreatmentIdEditRouteImport.update({
    id: '/trattamenti/$treatmentId/edit',
    path: '/trattamenti/$treatmentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const RaccoltiHarvestIdEditRoute = RaccoltiHarvestIdEditRouteImport.update({
  id: '/raccolti/$harvestId/edit',
  path: '/raccolti/$harvestId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsHiveIdNewRoute = InspectionsHiveIdNewRouteImport.update({
  id: '/inspections/$hiveId/new',
  path: '/inspections/$hiveId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HivesHiveIdEditRoute = HivesHiveIdEditRouteImport.update({
  id: '/hives/$hiveId/edit',
  path: '/hives/$hiveId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiariesApiaryIdSuggerimentiRoute =
  ApiariesApiaryIdSuggerimentiRouteImport.update({
    id: '/apiaries/$apiaryId/suggerimenti',
    path: '/apiaries/$apiaryId/suggerimenti',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiariesApiaryIdMeteoRoute = ApiariesApiaryIdMeteoRouteImport.update({
  id: '/apiaries/$apiaryId/meteo',
  path: '/apiaries/$apiaryId/meteo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiariesApiaryIdEditRoute = ApiariesApiaryIdEditRouteImport.update({
  id: '/apiaries/$apiaryId/edit',
  path: '/apiaries/$apiaryId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthApiariesApiaryIdRoute = AuthApiariesApiaryIdRouteImport.update({
  id: '/apiaries/$apiaryId',
  path: '/apiaries/$apiaryId',
  getParentRoute: () => AuthRoute,
} as any)
const HivesHiveIdInspectionsInspectionIdRoute =
  HivesHiveIdInspectionsInspectionIdRouteImport.update({
    id: '/hives/$hiveId/inspections/$inspectionId',
    path: '/hives/$hiveId/inspections/$inspectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiariesApiaryIdHivesNewRoute =
  ApiariesApiaryIdHivesNewRouteImport.update({
    id: '/apiaries/$apiaryId/hives/new',
    path: '/apiaries/$apiaryId/hives/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthHivesHiveIdInspectionsRoute =
  AuthHivesHiveIdInspectionsRouteImport.update({
    id: '/hives/$hiveId/inspections',
    path: '/hives/$hiveId/inspections',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/piu': typeof PiuRoute
  '/previsioni': typeof PrevisioniRoute
  '/set-password': typeof SetPasswordRoute
  '/statistiche': typeof StatisticheRoute
  '/arnie': typeof AuthArnieRoute
  '/calendario': typeof AuthCalendarioRoute
  '/home': typeof AuthHomeRoute
  '/raccolti': typeof AuthRaccoltiRoute
  '/trattamenti': typeof AuthTrattamentiRoute
  '/admin/attivita': typeof AdminAttivitaRoute
  '/admin/users': typeof AdminUsersRoute
  '/apiaries/new': typeof ApiariesNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/raccolti/new': typeof RaccoltiNewRoute
  '/trattamenti/new': typeof TrattamentiNewRoute
  '/apiaries/$apiaryId': typeof AuthApiariesApiaryIdRoute
  '/apiaries/$apiaryId/edit': typeof ApiariesApiaryIdEditRoute
  '/apiaries/$apiaryId/meteo': typeof ApiariesApiaryIdMeteoRoute
  '/apiaries/$apiaryId/suggerimenti': typeof ApiariesApiaryIdSuggerimentiRoute
  '/hives/$hiveId/edit': typeof HivesHiveIdEditRoute
  '/inspections/$hiveId/new': typeof InspectionsHiveIdNewRoute
  '/raccolti/$harvestId/edit': typeof RaccoltiHarvestIdEditRoute
  '/trattamenti/$treatmentId/edit': typeof TrattamentiTreatmentIdEditRoute
  '/hives/$hiveId/inspections': typeof AuthHivesHiveIdInspectionsRoute
  '/apiaries/$apiaryId/hives/new': typeof ApiariesApiaryIdHivesNewRoute
  '/hives/$hiveId/inspections/$inspectionId': typeof HivesHiveIdInspectionsInspectionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/piu': typeof PiuRoute
  '/previsioni': typeof PrevisioniRoute
  '/set-password': typeof SetPasswordRoute
  '/statistiche': typeof StatisticheRoute
  '/arnie': typeof AuthArnieRoute
  '/calendario': typeof AuthCalendarioRoute
  '/home': typeof AuthHomeRoute
  '/raccolti': typeof AuthRaccoltiRoute
  '/trattamenti': typeof AuthTrattamentiRoute
  '/admin/attivita': typeof AdminAttivitaRoute
  '/admin/users': typeof AdminUsersRoute
  '/apiaries/new': typeof ApiariesNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/raccolti/new': typeof RaccoltiNewRoute
  '/trattamenti/new': typeof TrattamentiNewRoute
  '/': typeof AuthIndexRoute
  '/apiaries/$apiaryId': typeof AuthApiariesApiaryIdRoute
  '/apiaries/$apiaryId/edit': typeof ApiariesApiaryIdEditRoute
  '/apiaries/$apiaryId/meteo': typeof ApiariesApiaryIdMeteoRoute
  '/apiaries/$apiaryId/suggerimenti': typeof ApiariesApiaryIdSuggerimentiRoute
  '/hives/$hiveId/edit': typeof HivesHiveIdEditRoute
  '/inspections/$hiveId/new': typeof InspectionsHiveIdNewRoute
  '/raccolti/$harvestId/edit': typeof RaccoltiHarvestIdEditRoute
  '/trattamenti/$treatmentId/edit': typeof TrattamentiTreatmentIdEditRoute
  '/hives/$hiveId/inspections': typeof AuthHivesHiveIdInspectionsRoute
  '/apiaries/$apiaryId/hives/new': typeof ApiariesApiaryIdHivesNewRoute
  '/hives/$hiveId/inspections/$inspectionId': typeof HivesHiveIdInspectionsInspectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/piu': typeof PiuRoute
  '/previsioni': typeof PrevisioniRoute
  '/set-password': typeof SetPasswordRoute
  '/statistiche': typeof StatisticheRoute
  '/_auth/arnie': typeof AuthArnieRoute
  '/_auth/calendario': typeof AuthCalendarioRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/raccolti': typeof AuthRaccoltiRoute
  '/_auth/trattamenti': typeof AuthTrattamentiRoute
  '/admin/attivita': typeof AdminAttivitaRoute
  '/admin/users': typeof AdminUsersRoute
  '/apiaries/new': typeof ApiariesNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/raccolti/new': typeof RaccoltiNewRoute
  '/trattamenti/new': typeof TrattamentiNewRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/apiaries/$apiaryId': typeof AuthApiariesApiaryIdRoute
  '/apiaries/$apiaryId/edit': typeof ApiariesApiaryIdEditRoute
  '/apiaries/$apiaryId/meteo': typeof ApiariesApiaryIdMeteoRoute
  '/apiaries/$apiaryId/suggerimenti': typeof ApiariesApiaryIdSuggerimentiRoute
  '/hives/$hiveId/edit': typeof HivesHiveIdEditRoute
  '/inspections/$hiveId/new': typeof InspectionsHiveIdNewRoute
  '/raccolti/$harvestId/edit': typeof RaccoltiHarvestIdEditRoute
  '/trattamenti/$treatmentId/edit': typeof TrattamentiTreatmentIdEditRoute
  '/_auth/hives/$hiveId/inspections': typeof AuthHivesHiveIdInspectionsRoute
  '/apiaries/$apiaryId/hives/new': typeof ApiariesApiaryIdHivesNewRoute
  '/hives/$hiveId/inspections/$inspectionId': typeof HivesHiveIdInspectionsInspectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/piu'
    | '/previsioni'
    | '/set-password'
    | '/statistiche'
    | '/arnie'
    | '/calendario'
    | '/home'
    | '/raccolti'
    | '/trattamenti'
    | '/admin/attivita'
    | '/admin/users'
    | '/apiaries/new'
    | '/auth/callback'
    | '/raccolti/new'
    | '/trattamenti/new'
    | '/apiaries/$apiaryId'
    | '/apiaries/$apiaryId/edit'
    | '/apiaries/$apiaryId/meteo'
    | '/apiaries/$apiaryId/suggerimenti'
    | '/hives/$hiveId/edit'
    | '/inspections/$hiveId/new'
    | '/raccolti/$harvestId/edit'
    | '/trattamenti/$treatmentId/edit'
    | '/hives/$hiveId/inspections'
    | '/apiaries/$apiaryId/hives/new'
    | '/hives/$hiveId/inspections/$inspectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/piu'
    | '/previsioni'
    | '/set-password'
    | '/statistiche'
    | '/arnie'
    | '/calendario'
    | '/home'
    | '/raccolti'
    | '/trattamenti'
    | '/admin/attivita'
    | '/admin/users'
    | '/apiaries/new'
    | '/auth/callback'
    | '/raccolti/new'
    | '/trattamenti/new'
    | '/'
    | '/apiaries/$apiaryId'
    | '/apiaries/$apiaryId/edit'
    | '/apiaries/$apiaryId/meteo'
    | '/apiaries/$apiaryId/suggerimenti'
    | '/hives/$hiveId/edit'
    | '/inspections/$hiveId/new'
    | '/raccolti/$harvestId/edit'
    | '/trattamenti/$treatmentId/edit'
    | '/hives/$hiveId/inspections'
    | '/apiaries/$apiaryId/hives/new'
    | '/hives/$hiveId/inspections/$inspectionId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/piu'
    | '/previsioni'
    | '/set-password'
    | '/statistiche'
    | '/_auth/arnie'
    | '/_auth/calendario'
    | '/_auth/home'
    | '/_auth/raccolti'
    | '/_auth/trattamenti'
    | '/admin/attivita'
    | '/admin/users'
    | '/apiaries/new'
    | '/auth/callback'
    | '/raccolti/new'
    | '/trattamenti/new'
    | '/_auth/'
    | '/_auth/apiaries/$apiaryId'
    | '/apiaries/$apiaryId/edit'
    | '/apiaries/$apiaryId/meteo'
    | '/apiaries/$apiaryId/suggerimenti'
    | '/hives/$hiveId/edit'
    | '/inspections/$hiveId/new'
    | '/raccolti/$harvestId/edit'
    | '/trattamenti/$treatmentId/edit'
    | '/_auth/hives/$hiveId/inspections'
    | '/apiaries/$apiaryId/hives/new'
    | '/hives/$hiveId/inspections/$inspectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PiuRoute: typeof PiuRoute
  PrevisioniRoute: typeof PrevisioniRoute
  SetPasswordRoute: typeof SetPasswordRoute
  StatisticheRoute: typeof StatisticheRoute
  AdminAttivitaRoute: typeof AdminAttivitaRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiariesNewRoute: typeof ApiariesNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RaccoltiNewRoute: typeof RaccoltiNewRoute
  TrattamentiNewRoute: typeof TrattamentiNewRoute
  ApiariesApiaryIdEditRoute: typeof ApiariesApiaryIdEditRoute
  ApiariesApiaryIdMeteoRoute: typeof ApiariesApiaryIdMeteoRoute
  ApiariesApiaryIdSuggerimentiRoute: typeof ApiariesApiaryIdSuggerimentiRoute
  HivesHiveIdEditRoute: typeof HivesHiveIdEditRoute
  InspectionsHiveIdNewRoute: typeof InspectionsHiveIdNewRoute
  RaccoltiHarvestIdEditRoute: typeof RaccoltiHarvestIdEditRoute
  TrattamentiTreatmentIdEditRoute: typeof TrattamentiTreatmentIdEditRoute
  ApiariesApiaryIdHivesNewRoute: typeof ApiariesApiaryIdHivesNewRoute
  HivesHiveIdInspectionsInspectionIdRoute: typeof HivesHiveIdInspectionsInspectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistiche': {
      id: '/statistiche'
      path: '/statistiche'
      fullPath: '/statistiche'
      preLoaderRoute: typeof StatisticheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsioni': {
      id: '/previsioni'
      path: '/previsioni'
      fullPath: '/previsioni'
      preLoaderRoute: typeof PrevisioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piu': {
      id: '/piu'
      path: '/piu'
      fullPath: '/piu'
      preLoaderRoute: typeof PiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/trattamenti/new': {
      id: '/trattamenti/new'
      path: '/trattamenti/new'
      fullPath: '/trattamenti/new'
      preLoaderRoute: typeof TrattamentiNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raccolti/new': {
      id: '/raccolti/new'
      path: '/raccolti/new'
      fullPath: '/raccolti/new'
      preLoaderRoute: typeof RaccoltiNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiaries/new': {
      id: '/apiaries/new'
      path: '/apiaries/new'
      fullPath: '/apiaries/new'
      preLoaderRoute: typeof ApiariesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attivita': {
      id: '/admin/attivita'
      path: '/admin/attivita'
      fullPath: '/admin/attivita'
      preLoaderRoute: typeof AdminAttivitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/trattamenti': {
      id: '/_auth/trattamenti'
      path: '/trattamenti'
      fullPath: '/trattamenti'
      preLoaderRoute: typeof AuthTrattamentiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/raccolti': {
      id: '/_auth/raccolti'
      path: '/raccolti'
      fullPath: '/raccolti'
      preLoaderRoute: typeof AuthRaccoltiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendario': {
      id: '/_auth/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthCalendarioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/arnie': {
      id: '/_auth/arnie'
      path: '/arnie'
      fullPath: '/arnie'
      preLoaderRoute: typeof AuthArnieRouteImport
      parentRoute: typeof AuthRoute
    }
    '/trattamenti/$treatmentId/edit': {
      id: '/trattamenti/$treatmentId/edit'
      path: '/trattamenti/$treatmentId/edit'
      fullPath: '/trattamenti/$treatmentId/edit'
      preLoaderRoute: typeof TrattamentiTreatmentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raccolti/$harvestId/edit': {
      id: '/raccolti/$harvestId/edit'
      path: '/raccolti/$harvestId/edit'
      fullPath: '/raccolti/$harvestId/edit'
      preLoaderRoute: typeof RaccoltiHarvestIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/$hiveId/new': {
      id: '/inspections/$hiveId/new'
      path: '/inspections/$hiveId/new'
      fullPath: '/inspections/$hiveId/new'
      preLoaderRoute: typeof InspectionsHiveIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hives/$hiveId/edit': {
      id: '/hives/$hiveId/edit'
      path: '/hives/$hiveId/edit'
      fullPath: '/hives/$hiveId/edit'
      preLoaderRoute: typeof HivesHiveIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiaries/$apiaryId/suggerimenti': {
      id: '/apiaries/$apiaryId/suggerimenti'
      path: '/apiaries/$apiaryId/suggerimenti'
      fullPath: '/apiaries/$apiaryId/suggerimenti'
      preLoaderRoute: typeof ApiariesApiaryIdSuggerimentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiaries/$apiaryId/meteo': {
      id: '/apiaries/$apiaryId/meteo'
      path: '/apiaries/$apiaryId/meteo'
      fullPath: '/apiaries/$apiaryId/meteo'
      preLoaderRoute: typeof ApiariesApiaryIdMeteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiaries/$apiaryId/edit': {
      id: '/apiaries/$apiaryId/edit'
      path: '/apiaries/$apiaryId/edit'
      fullPath: '/apiaries/$apiaryId/edit'
      preLoaderRoute: typeof ApiariesApiaryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/apiaries/$apiaryId': {
      id: '/_auth/apiaries/$apiaryId'
      path: '/apiaries/$apiaryId'
      fullPath: '/apiaries/$apiaryId'
      preLoaderRoute: typeof AuthApiariesApiaryIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/hives/$hiveId/inspections/$inspectionId': {
      id: '/hives/$hiveId/inspections/$inspectionId'
      path: '/hives/$hiveId/inspections/$inspectionId'
      fullPath: '/hives/$hiveId/inspections/$inspectionId'
      preLoaderRoute: typeof HivesHiveIdInspectionsInspectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apiaries/$apiaryId/hives/new': {
      id: '/apiaries/$apiaryId/hives/new'
      path: '/apiaries/$apiaryId/hives/new'
      fullPath: '/apiaries/$apiaryId/hives/new'
      preLoaderRoute: typeof ApiariesApiaryIdHivesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/hives/$hiveId/inspections': {
      id: '/_auth/hives/$hiveId/inspections'
      path: '/hives/$hiveId/inspections'
      fullPath: '/hives/$hiveId/inspections'
      preLoaderRoute: typeof AuthHivesHiveIdInspectionsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthArnieRoute: typeof AuthArnieRoute
  AuthCalendarioRoute: typeof AuthCalendarioRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthRaccoltiRoute: typeof AuthRaccoltiRoute
  AuthTrattamentiRoute: typeof AuthTrattamentiRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthApiariesApiaryIdRoute: typeof AuthApiariesApiaryIdRoute
  AuthHivesHiveIdInspectionsRoute: typeof AuthHivesHiveIdInspectionsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthArnieRoute: AuthArnieRoute,
  AuthCalendarioRoute: AuthCalendarioRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthRaccoltiRoute: AuthRaccoltiRoute,
  AuthTrattamentiRoute: AuthTrattamentiRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthApiariesApiaryIdRoute: AuthApiariesApiaryIdRoute,
  AuthHivesHiveIdInspectionsRoute: AuthHivesHiveIdInspectionsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PiuRoute: PiuRoute,
  PrevisioniRoute: PrevisioniRoute,
  SetPasswordRoute: SetPasswordRoute,
  StatisticheRoute: StatisticheRoute,
  AdminAttivitaRoute: AdminAttivitaRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiariesNewRoute: ApiariesNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RaccoltiNewRoute: RaccoltiNewRoute,
  TrattamentiNewRoute: TrattamentiNewRoute,
  ApiariesApiaryIdEditRoute: ApiariesApiaryIdEditRoute,
  ApiariesApiaryIdMeteoRoute: ApiariesApiaryIdMeteoRoute,
  ApiariesApiaryIdSuggerimentiRoute: ApiariesApiaryIdSuggerimentiRoute,
  HivesHiveIdEditRoute: HivesHiveIdEditRoute,
  InspectionsHiveIdNewRoute: InspectionsHiveIdNewRoute,
  RaccoltiHarvestIdEditRoute: RaccoltiHarvestIdEditRoute,
  TrattamentiTreatmentIdEditRoute: TrattamentiTreatmentIdEditRoute,
  ApiariesApiaryIdHivesNewRoute: ApiariesApiaryIdHivesNewRoute,
  HivesHiveIdInspectionsInspectionIdRoute:
    HivesHiveIdInspectionsInspectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
